#!/usr/bin/env python3
"""
GHOSTLINK AUTOMATION ARTIFACT
Generated by: GHOSTCORE_FINAL_MAX
Pipeline: P-01 (MAP) → P-17 (Execution)
Target: Google Forms - Claude Desktop Feedback
Compliance: R-01,R-02,R-03,R-04 (All output rules enforced)
"""

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import time
import sys

# ============================================================================
# CONFIGURATION SECTION - OPERATOR CUSTOMIZABLE
# ============================================================================

FORM_URL = "https://docs.google.com/forms/d/e/1FAIpQLScfF23aTWBmd6lNk-Pcv_AeM2BkgzN2V7XPKXLjFiEhvFmm-w/viewform?pli=1"

# Define your feedback responses here
FEEDBACK_DATA = {
    "feedback_text": """
    Feedback on Claude Desktop App:
    
    Strengths:
    - Excellent integration with local filesystem
    - Fast response times
    - Clean interface
    
    Areas for improvement:
    - Form automation capabilities could be enhanced
    - More granular control over tool execution
    - Better visualization of multi-step processes
    """,
    
    "bug_reports": """
    No critical bugs encountered during testing.
    Minor UI inconsistencies in dark mode.
    """,
    
    "feature_requests": """
    1. Native browser automation support
    2. Enhanced file system operations
    3. Built-in form filling capabilities
    4. Session persistence across restarts
    """,
    
    "additional_comments": """
    Overall excellent experience with the beta.
    Looking forward to future updates.
    """
}

# ============================================================================
# AUTOMATION LOGIC - GHOSTLINK KERNEL GENERATED
# ============================================================================

class GoogleFormAutomator:
    """
    Automated form filler using Selenium WebDriver
    Complies with: L-04 (Planning), L-07 (R&D Protocol)
    """
    
    def __init__(self, headless=False):
        """Initialize browser with options"""
        self.options = Options()
        if headless:
            self.options.add_argument('--headless')
        self.options.add_argument('--no-sandbox')
        self.options.add_argument('--disable-dev-shm-usage')
        self.options.add_argument('--disable-blink-features=AutomationControlled')
        self.driver = None
        
    def setup_driver(self):
        """Setup Chrome WebDriver"""
        print("[GHOSTLINK] Initializing WebDriver...")
        service = Service(ChromeDriverManager().install())
        self.driver = webdriver.Chrome(service=service, options=self.options)
        self.driver.maximize_window()
        print("[GHOSTLINK] WebDriver initialized successfully")
        
    def navigate_to_form(self, url):
        """Navigate to the target form"""
        print(f"[GHOSTLINK] Navigating to: {url}")
        self.driver.get(url)
        time.sleep(2)  # Wait for page load
        print("[GHOSTLINK] Page loaded")
        
    def wait_for_element(self, by, value, timeout=10):
        """Wait for element to be present"""
        try:
            element = WebDriverWait(self.driver, timeout).until(
                EC.presence_of_element_located((by, value))
            )
            return element
        except Exception as e:
            print(f"[GHOSTLINK ERROR] Element not found: {value}")
            print(f"[GHOSTLINK ERROR] Exception: {str(e)}")
            return None
    
    def fill_text_field(self, field_selector, text):
        """Fill a text field or textarea"""
        try:
            # Try multiple selector strategies
            selectors = [
                (By.CSS_SELECTOR, f"textarea[aria-label*='{field_selector}']"),
                (By.CSS_SELECTOR, f"input[aria-label*='{field_selector}']"),
                (By.XPATH, f"//textarea[contains(@aria-label, '{field_selector}')]"),
                (By.XPATH, f"//input[contains(@aria-label, '{field_selector}')]"),
                (By.CSS_SELECTOR, "textarea"),
                (By.CSS_SELECTOR, "input[type='text']")
            ]
            
            element = None
            for by, selector in selectors:
                try:
                    elements = self.driver.find_elements(by, selector)
                    if elements:
                        element = elements[0]
                        break
                except:
                    continue
            
            if element:
                element.clear()
                element.send_keys(text)
                print(f"[GHOSTLINK] Filled field: {field_selector}")
                return True
            else:
                print(f"[GHOSTLINK WARNING] Field not found: {field_selector}")
                return False
                
        except Exception as e:
            print(f"[GHOSTLINK ERROR] Failed to fill field: {field_selector}")
            print(f"[GHOSTLINK ERROR] Exception: {str(e)}")
            return False
    
    def fill_all_fields(self, data):
        """Fill all form fields with provided data"""
        print("[GHOSTLINK] Beginning form population...")
        
        # Wait for form to be fully loaded
        time.sleep(3)
        
        # Get all text input fields
        text_fields = self.driver.find_elements(By.CSS_SELECTOR, "textarea, input[type='text']")
        print(f"[GHOSTLINK] Found {len(text_fields)} text input fields")
        
        # Fill fields in order
        field_index = 0
        for key, value in data.items():
            if field_index < len(text_fields):
                try:
                    text_fields[field_index].clear()
                    text_fields[field_index].send_keys(value)
                    print(f"[GHOSTLINK] Filled field {field_index + 1}: {key}")
                    time.sleep(0.5)
                    field_index += 1
                except Exception as e:
                    print(f"[GHOSTLINK ERROR] Failed to fill field {field_index}: {str(e)}")
        
        print("[GHOSTLINK] Form population complete")
        
    def submit_form(self, dry_run=True):
        """
        Submit the form
        dry_run=True: Preview only, don't actually submit
        dry_run=False: Actually submit the form
        """
        if dry_run:
            print("[GHOSTLINK] DRY RUN MODE - Form NOT submitted")
            print("[GHOSTLINK] Review the form in the browser window")
            print("[GHOSTLINK] Press Enter to close browser...")
            input()
        else:
            try:
                # Find submit button
                submit_selectors = [
                    (By.XPATH, "//span[contains(text(), 'Submit')]"),
                    (By.CSS_SELECTOR, "div[role='button'][aria-label*='Submit']"),
                    (By.XPATH, "//div[@role='button']//span[text()='Submit']")
                ]
                
                submit_button = None
                for by, selector in submit_selectors:
                    try:
                        submit_button = self.driver.find_element(by, selector)
                        if submit_button:
                            break
                    except:
                        continue
                
                if submit_button:
                    submit_button.click()
                    print("[GHOSTLINK] Form submitted successfully")
                    time.sleep(2)
                else:
                    print("[GHOSTLINK WARNING] Submit button not found")
                    
            except Exception as e:
                print(f"[GHOSTLINK ERROR] Failed to submit form: {str(e)}")
    
    def take_screenshot(self, filename="form_preview.png"):
        """Take screenshot for verification"""
        try:
            self.driver.save_screenshot(filename)
            print(f"[GHOSTLINK] Screenshot saved: {filename}")
        except Exception as e:
            print(f"[GHOSTLINK ERROR] Failed to save screenshot: {str(e)}")
    
    def cleanup(self):
        """Close browser and cleanup"""
        if self.driver:
            print("[GHOSTLINK] Closing browser...")
            self.driver.quit()
            print("[GHOSTLINK] Cleanup complete")

# ============================================================================
# MAIN EXECUTION
# ============================================================================

def main():
    """Main execution flow"""
    print("=" * 80)
    print("GHOSTLINK AUTOMATION SYSTEM")
    print("Target: Google Forms - Claude Desktop Feedback")
    print("=" * 80)
    print()
    
    # Initialize automator
    automator = GoogleFormAutomator(headless=False)
    
    try:
        # Setup
        automator.setup_driver()
        
        # Navigate
        automator.navigate_to_form(FORM_URL)
        
        # Fill form
        automator.fill_all_fields(FEEDBACK_DATA)
        
        # Take screenshot
        automator.take_screenshot("form_filled.png")
        
        # Submit (DRY RUN by default - review before submitting)
        print()
        print("=" * 80)
        print("FORM FILLED - READY FOR REVIEW")
        print("=" * 80)
        print()
        print("Options:")
        print("1. Press Enter to close without submitting (safe preview)")
        print("2. Manually click Submit in the browser window")
        print()
        
        automator.submit_form(dry_run=True)
        
    except Exception as e:
        print(f"[GHOSTLINK CRITICAL ERROR] {str(e)}")
        import traceback
        traceback.print_exc()
        
    finally:
        # Cleanup
        automator.cleanup()
        print("[GHOSTLINK] Automation complete")

if __name__ == "__main__":
    main()
