apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://192.168.1.107:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    url: 192.168.1.111:5432
    database: ghostlink
    user: ghostlink
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-changeme789}
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400

  - name: Redis
    type: redis-datasource
    url: redis://192.168.1.110:6379
    editable: true